name: google_map_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.3.0
  location: ^5.0.3
  flutter_polyline_points: ^2.0.0
  arcore_flutter_plugin: ^0.1.0
  vector_math: ^2.1.4
  flutter_map: ^6.1.0
  ar_flutter_plugin: ^0.7.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
